# Usage: conda env create -f environment.yaml

name: dpcr

channels:
  - defaults
  - pytorch
  - nvidia
  - conda-forge

dependencies:
  - python=3.9
  - cudatoolkit=11.6
  - pytorch==1.12.0
  - torchaudio==0.12.0
  - torchvision==0.13.0
  - matplotlib
  - tqdm
  - timm=0.6.12
  - ipykernel
  - scikit-learn

